
#
#  PRINT "remove old content"

#
#  PRINT "Organise ${COMPONENT} content"
#  mv ${COMPONENT}-main/* . && mv static/* . &&  rm -rf ${COMPONENT}-main README.md && mv localhost.conf /etc/nginx/default.d/roboshop.conf
#  CHECK_STAT $?
#
#
#  PRINT "update ${COMPONENT} configuration"
#  sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf
#  CHECK_STAT $?
#
#  PRINT "start Nginx service"
#  systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
#  CHECK_STAT $?
#
#}

- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import Common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#- name: Copy {{ COMPONENT }}  Config file
#  ansible.builtin.template:
#    src: roboshop.conf
#    dest: /etc/nginx/default.d/roboshop.conf
#  notify: Restart Nginx Service

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes




