- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove App Location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Create App Location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory
    
- name: Download & Extract {{ COMPONENT }} Component Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy {{ COMPONENT }} Code to App Location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/{{SUFFIX}}
    dest: "{{ APP_LOCATION }}"
    remote_src: yes
